### GET all generos
GET http://localhost:8080/generos

### GET genero by id
GET http://localhost:8080/generos/1

### POST create genero
POST http://localhost:8080/generos
Content-Type: application/json

{
  "descricao": "Ficção Científica"
}

### PUT update genero
PUT http://localhost:8080/generos/1
Content-Type: application/json

{
  "descricao": "Fantasia"
}

### DELETE genero by id
DELETE http://localhost:8080/generos/1